### ISSUE TITLE
Missing target while using actor_stream

### ISSUE THREAD

**Issue by fynjah** [justquick/django-activity-stream#245] opened 2015-06-10 10:16 UTC
hi.
I'm expecting troubles with `actor_stream(request.user)`. 

for example:

```
from actstream.models import actor_stream, Action
print actor_stream(request.user)[0].target # returns None
print Action.objects.all()[0].target # returns Target object
```

BUT:

```
from actstream.models import actor_stream, Action
print request.user.actor_actions.all()[0].target  # returns Target object
```

User model - this is a custom user model, configured as described in djangoproject tutorial. 
Target model looks like this:

```
class Task(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey('core_auth.User', blank=True, null=True)
    ... < more fields >
```

Let me show you:

```
>>> from actstream.models import actor_stream, Action
>>> from core_auth.models import User
>>> u = User.objects.get(username='fynjah')
>>> actor_stream(u)[0].target # None
>>> x = actor_stream(u)[0]
>>> x
<Action: fynjah changed status DONE 58 minutes ago>
# BUT:
>>> x.target_content_type
<ContentType: Task>
>>> x.target
>>> x.target_object_id
u'f08ae5ab-8c07-4929-9021-62c867f0d081'
# AND:
>>> u.actor_actions.all()[0].target
<Task: wdstrm compositing>
```

What am i doing wrong :\

**Comment by justquick** [comment] 2015-06-15 04:47
what is your exact issue? i think it's "target returns None when using actor_stream" but i want to make sure

also can you please provide a more complete example that illustrates the problem? i dont see how the Action and Task models are being created

**Comment by fynjah** [comment] 2015-06-15 07:22
Hi. Yes, the exact issue is "target returns None when using actor_stream".

Here is how actions are being created.

    @receiver(pre_save, sender=Task)
    def detect_task_status(sender, instance, **kwargs):
        try:
            obj = Task.objects.get(pk=instance.pk)
        except Task.DoesNotExist:
            # Object is new, so field hasn't technically changed, but you
            # may want to do something else here.
            pass
        else:
            if not obj.status == instance.status:  # Field has changed
                logged_in = LoggedInUser() 
                # LoggedInUser is a singleton, which processed in middleware
                # and returns request.user
                user = logged_in.user
                action.send(user,
                    verb='changed status',
                    action_object=instance.status,
                    target=instance,
                    old_status={
                        'name': obj.status.name,
                        'id': obj.status.id,
                        'color': obj.status.color
                        },
                    action_type='change_status')

Once action is created, i'm trying to receive actor_stream 


    @login_required
    def get_stream(request):
        from actstream.models import actor_stream, Action
        mdict = {'actions':actor_stream(request.user)}
        return render_to_response('user/stream.html', mdict, context_instance=RequestContext(request))

And then target returns None.
But if i'm doing like this, everything is ok:


    @login_required
    def get_stream(request):
        from actstream.models import actor_stream, Action
        mdict = {'actions': request.user.actor_actions.all()}
        return render_to_response('user/stream.html', mdict, context_instance=RequestContext(request))

**Comment by justquick** [comment] 2015-06-15 14:05
are you using the Action.public bool at any point? the actor_stream should return essentially `request.user.actor_actions.public(**kwargs)`

**Comment by fynjah** [comment] 2015-06-15 14:21
No, i'm not using public anywhere. Actually, all code i'm using at this moment i've posted above.

I've just checked actions in DB - they are all marked as `public=true`

**Comment by justquick** [comment] 2015-06-16 12:24
hrm very weird. i notice you are using the pre_save signal, can you try switching to the post_save? i believe in pre_save the object will not have an id yet which throws off GFK relationships. that's the only thing that seems out of place to me. if that doesnt help then im not sure what else to do. luckily you have a working implementation so just the actor_stream is broken but you can complete your view.

**Comment by fynjah** [comment] 2015-06-16 13:18
Hi. In pre_save signal i verify does object exist or not.
here:

        try:
            obj = Task.objects.get(pk=instance.pk)
        except Task.DoesNotExist:
            # Object is new, so field hasn't technically changed
            pass
        else:
         .......

So if object already exists and `status` field is changed - than create action.

And even more, in the first post i've showed this:

    >>> actor_stream(u)[0].target # None
    >>> x = actor_stream(u)[0]
    >>> x # An action exists
    <Action: fynjah changed status DONE 58 minutes ago>
    >>> x.target_content_type
    <ContentType: Task> # Content type exists
    >>> x.target # None (!!!)
    >>> x.target_object_id # target_object_id exists
    u'f08ae5ab-8c07-4929-9021-62c867f0d081'

So, as you can see, `target_content_type` and `target_object_id` exists, but `target` field retuns `None`

About issue #246 - I've tested `request.user.actor_actions.all().fetch_generic_relations()` and `target` again returns `None` !
Here is log from shell:

    >>> from core.models import User
    >>> u = User.objects.get(username='fynjah')
    >>> u.actor_actions.all().fetch_generic_relations()
    [<Action: fynjah changed status APPROVED 1 day ago>, <Action: fynjah changed status COMMENTED 4 days, 3 hours ago>, <Action: fynjah changed status DONE 4 days, 3 hours ago>, <Action: fynjah changed status HOLD 4 days, 3 hours ago>, '...(remaining elements truncated)...']
    >>> x = u.actor_actions.all().fetch_generic_relations()
    >>> x = x[0]
    >>> x.target # None (!!!)
    >>> x.target_content_type # Exists
    <ContentType: Task>
    >>> x.target_object_id # Exists
    u'1174029a-3cf8-4e93-aaed-1080a3fee417'
    
I think it's all about `uuid` as `primary key` in `Task` model

**Comment by 5a1t** [comment] 2015-10-02 00:13
I'm having this same problem with using actor_stream or any_stream.  Getting none for action_object.  Verified action_object exists in the DB and I can access it directly (without using streams).  Have not tried target or other streams.

Setting FETCH_RELATIONS to false (mentioned in other thread with similar issue) did not seem to fix things.

Streams basically unusable currently.

**Comment by amyth** [comment] 2015-10-27 09:36
I am facing a similar issue with using the `user_stream` via the template tag as follows:

```
{% activity_stream 'user' request.user %}
{% for action in stream %}
    {{ action.pk }} : {{ action.target }} : {{ action.action_object }}
{% endfor %}
``` 

The above template renders as follows:

```
7 : None : None
6 : None : None
5 : Amyth Arora : None
3 : Amyth Arora : None
1 : None : None
```

And when I do the following in the shell for the above actor object:

```
In [15]: for action in actor.actor_actions.all():
   ....:     print action.pk, action.target, action.action_object
   ....:
7 Flowers By Irene None
6 None Central Perk
5 Amyth Arora None
3 Amyth Arora None
1 None None
```

So you see for action object 7, the target exists and I can see it in the shell and for action object 6, target is none but action_object exists. But in the template for actions 6,7 both target and action_objects is none.

**Comment by oaubert** [comment] 2016-05-17 14:07
Same issue here, in the same context (using uuids as primary keys). This kind of issue is frequent in django extensions, uuids are not a smooth ride.

**Comment by yuukari** [comment] 2017-07-31 21:47
Word for word the same problem i'm facing only with models that have UUIDs as PKs.

**Comment by johnyoonh** [comment] 2018-07-26 03:02
Yup this happens to me too

**Comment by faxioman** [comment] 2018-09-02 10:06
Are you guys using django polymorphic in your projects?

**Comment by auvipy** [comment] 2018-09-03 15:57
are you facing it while using django-polymorphic with act-stream?

**Comment by faxioman** [comment] 2018-09-03 20:13
Yes, but it's a polymorphic bug.
In class GFKQuerySet, method fetch_generic_relations the queryset returned by
```
qs.prefetch_related(*[g.name for g in gfk_fields])
```
sets all the three generic relation to None.
django-polymorphic has some strange behaviours when using prefetch_related (eg. https://github.com/django-polymorphic/django-polymorphic/issues/68).
 A workaround is to set the FETCH_RELATIONS setting to False.

**Comment by timur-orudzhov** [comment] 2019-04-09 09:52
It's not only django-polymorphic's bug, it's probably bug related to django itself, @oaubert have already mentioned prefetch_related is not working when using UUID as pk. This what i found so far – https://code.djangoproject.com/ticket/24912

**Comment by timur-orudzhov** [comment] 2019-04-09 09:58
Does anybody know why django still have this bug for postgres, but for non-postgres  db it was fixed?

**Comment by timur-orudzhov** [comment] 2019-04-10 09:16
I've created ticket for django for that case – https://code.djangoproject.com/ticket/30343#ticket.

**Comment by auvipy** [comment] 2019-04-15 01:42
thanks for reporting timur!! the issue is fixed in Django https://github.com/django/django/pull/11211

**Closed by auvipy** 2019-04-15 01:42 UTC
Labels: weirdness

**Comment by cobyrne09** [comment] 2020-01-07 16:38
@auvipy Even though the change is made in Django, based on a brief look at the code, it appears as though the Action model would need to be changed to accomodate UUIDs. I ended up using UUID's as secondary keys for my models, and having actstream hook up with my standard autoincrement pks. If you want to use UUID's and actstream, this is probably the best you can do until the code fixes are in place. Unfortunately I am not competent enough to make said code changes.
